[project]
name = "heart-go"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.9",
    "pillow>=12.0.0",
]

[dependency-groups]
dev = [
    "aws-sam-cli>=1.148.0",
]
